name: " 🚀 WP Lab deploy to Prod "
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install
      

  deploy:
    runs-on: ubuntu-latest
    needs: checks
    if: ${{github.event_name == 'push'}}
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install|
           lint:js
          
    - name: Zip Theme
      run: npm run archive
        
    - name: Deploy Theme
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude="node_modules" --exclude=".github" --exclude=".git"
        rsh: -o PubkeyAcceptedKeyTypes=*ssh-rsa -o HostKeyAlgorithms=+ssh-rsa
        path: ./package/
        remote_path: ${{secrets.THEME_PATH}}
        remote_host: ${{ secrets.THEME_HOST }}
        remote_port: ${{ secrets.HOST_PORT }}
        remote_user: ${{ secrets.HOST_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_key_pass: ${{ secrets.HOST_PASS }}
        
    - name: Accesing to server and unzip
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.THEME_HOST }}
        user: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        pass: ${{ secrets.HOST_PASS }}
        run: |
          cd ${{secrets.THEME_PATH}}
          pwd
          ls
          rm mix-manifest.json
          rm ns-script.js
          rm ns-script.js.LICENSE.txt
          rm ns-styles.css
          rm -rf .git
          unzip custom-gutenberg-blocks-nicasource.zip
          rm *.zip