name: " 🚀 WP Lab deploy "
on:
  push:
    branches:
      - main
 
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install
      

  deploy:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install
          
    - name: Zip Theme
      run: npm run archive
        
    - name: Deploy Theme
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude="node_modules" --exclude=".github" --exclude=".git"
        rsh: -o PubkeyAcceptedKeyTypes=*ssh-rsa -o HostKeyAlgorithms=+ssh-rsa
        path: ./dist/
        remote_path: ./html/wp-content/themes/wplabtheme
        remote_host: ${{ secrets.SERVER_DEV_HOST }}
        remote_port: ${{ secrets.SERVER_DEV_PORT }}
        remote_user: ${{ secrets.SERVER_DEV_USER }}
        remote_key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
        remote_key_pass: ${{ secrets.SERVER_DEV_PASS }}
        
    - name: Cleaning
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_DEV_HOST }}
        user: ${{ secrets.SERVER_DEV_USER }}
        key: ${{ secrets.SSH_DEV_PRIVATE_KEY}}
        pass: ${{ secrets.SERVER_DEV_PASS }}
        run: |
          cd ${{secrets.PLUGIN_DEV_PATH}}
          pwd
          ls
          rm mix-manifest.json
          rm ns-script.js
          rm ns-script.js.LICENSE.txt
          rm ns-styles.css
          rm -rf .git
          unzip custom-gutenberg-blocks-nicasource.zip
          rm *.zip